version: '3.1'

services:

    node:
        build:
            context: ./
            dockerfile: ./docker/node/Dockerfile
        command: [ 'yarn', 'build' ]

    redis:
        build:
            context: ./
            dockerfile: ./docker/redis/Dockerfile
        volumes:
            - 'redis_data:/data'

    mariadb:
        build:
            context: ./
            dockerfile: ./docker/mariadb/Dockerfile
        restart: on-failure
        env_file:
          - '.env'
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1']
            interval: 1m30s
            timeout: 30s
            retries: 10
        volumes:
            - 'mariadb_data:/var/lib/mysql'

    php:
        build:
            context: ./
            dockerfile: ./docker/php-fpm/Dockerfile
        env_file:
          - '.env'

    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - '80:80'
            - '443:443'

volumes:
    redis_data:
        driver: local
    mariadb_data:
        driver: local
